### ISSUE TITLE
Need to specify encoding order

### ISSUE THREAD

**Issue by emanjon** [EricssonResearch/CBOR-certificates#27]
Maps and arrays need to be encoded in the same order as the sequence or set in the DER encoding.

**Comment by highlunder** [comment]
Agree, but where do you think this should be specified? We need to provide a new more complex example cert at some (later) point, but to address the issue now, do you see some additional text in the "Message Fields" section or something else?

**Comment by emanjon** [comment]
Somewhere where it fits the best. I guess it needs to be specified for SEQUANCE and SET with variable length. If we have done thing correctly these should correspond to CBOR arrays and maps.

**Comment by emanjon** [comment]
Done
