### ISSUE TITLE
Example with IEEE 802.1AR

### ISSUE THREAD

**Issue by gselander** [EricssonResearch/CBOR-certificates#59]
DevIDs specified in IEEE 802.1AR are RFC 5280 conformant X.509 certificates. Does the example in the appendix cover IEE802.1AR? Do we need to make particular optimizations to enable compact encoding of DevIDs or are the optimizations to support RFC 7925 enough?

**Comment by emanjon** [comment]
Check that IEEE 802.1 AR certificates can be encoded. Reference IEEE 802.1 AR.

**Comment by emanjon** [comment]
The -04 version did support IEEE 802.1AR DevID but not in a very optimized way. I have made commits to reference 802.1AR DevID and to treat it as an equal optimization target as RFC 7925. -05 handels  IEEE 802.1AR DevID lika a charm.

We should definitly have a  IEEE 802.1AR DevID example. The RFC 7925 example is not a valid IEEE 802.1AR DevID

**Comment by gselander** [comment]
Replaced by #69
